from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class AgentState(BaseModel):
    """
    The Shared Notebook (State) for the Multiagent system.
    Every agent reads from and writes to this structure to communicate.
    """
    user_prompt: str = Field(
        default="", 
        description="The raw academic search or question input from the student."
    )
    
    current_specialist: str = Field(
        default="manager", 
        description="The active sub-agent assigned to the task: 'manager', 'admin', 'thesis', or 'library'."
    )
    
    routing_reasoning: Optional[str] = Field(
        default=None, 
        description="The explanation behind why the Manager routed the task to a specific specialist."
    )
    
    raw_crawled_data: Optional[str] = Field(
        default=None, 
        description="The unstructured text, links, or tables pulled live from the university website by the browser tool."
    )
    
    agent_logs: List[str] = Field(
        default_factory=list, 
        description="Internal operational timeline logs streamed back to the UI (e.g., 'Launching browser...')."
    )
    
    final_compiled_answer: Optional[str] = Field(
        default=None, 
        description="The structured, human-friendly response generated by the manager to be displayed on the frontend UI."
    )